[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "EMAIL_HOST,EMAIL_USER,EMAIL_PASS,EMAIL_PORT,EMAIL_SECURE,EMAIL_TO"
  SECRETS_SCAN_OMIT_PATHS = ".next/**,out/**,build/**"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200